### ISSUE TITLE
"Upload New Files" in Project View drop-down menu does not work

### ISSUE THREAD

**Issue by llamsam** [redivis/meta#86] opened 2017-09-26 03:25 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Browser** (e.g., Chrome, Safari, etc.): Chrome

**What happened**: In the project view, there is an ellipsis drop-down menu with an "upload new files" option. Nothing happens when clicking on it.

**What you expected to happen**: I expected a menu to appear to allow me to upload a .csv file.

**How to reproduce it** (as minimally and precisely as possible): See above.

**Anything else do we need to know**: No

**Comment by imathews** [comment] 2017-09-26 21:43
Thanks for the issue @llamsam! Sorry for the confusion, this was a placeholder for a feature that we haven't fully rolled out yet (but will in the coming weeks).

I'm going to close this since it's a duplicate of #78, and will update that issues as this fix goes live.

**Closed by imathews** 2017-09-26 21:43 UTC
