### ISSUE TITLE
Create a value list from the clipboard

### ISSUE THREAD

**Issue by johardi** [redivis/meta#168] opened 2019-11-20 23:38 UTC
**What is the problem you'd like us to address**
It's time-consuming to copy-and-paste one-by-one the value item to create a value list. I have a long list of values in my notepad and I just want to be able to copy-and-paste everything. I know there's an option to store the list in a CSV file and import it, but I want to create the value list from the clipboard.

**Describe a solution (if you have one in mind)**
Redivis is able to detect automatically a value separator (e.g., comma, tab, newline) from the clipboard and make a list from those values.

**Describe other related products we could check out (if applicable)**
N/A

**Any additional context**
N/A

**Comment by imathews** [comment] 2019-11-22 18:15
@johardi Redivis should be able to recognize tabs and line breaks when pasted in from the clipboard. E.g.,
```
123	436
// or
123	
436
```
Is this not working for you? Currently commas as separators aren't recognized (because the value `123,456` is a valid literal), but it might be worth it to reconsider.

**Comment by johardi** [comment] 2019-12-04 00:46
This list was recognized partially:
```
AL	Alabama
AK	Alaska
AZ	Arizona
AR	Arkansas
CA	California
CO	Colorado
CT	Connecticut
DE	Delaware
FL	Florida
GA	Georgia
HI	Hawaii
ID	Idaho
IL	Illinois
IN	Indiana
IA	Iowa
KS	Kansas
KY	Kentucky
LA	Louisiana
ME	Maine
MD	Maryland
MA	Massachusetts
MI	Michigan
MN	Minnesota
MS	Mississippi
MO	Missouri
MT	Montana
NE	Nebraska
NV	Nevada
NH	New Hampshire
NJ	New Jersey
NM	New Mexico
NY	New York
NC	North Carolina
ND	North Dakota
OH	Ohio
OK	Oklahoma
OR	Oregon
PA	Pennsylvania
RI	Rhode Island
SC	South Carolina
SD	South Dakota
TN	Tennessee
TX	Texas
UT	Utah
VT	Vermont
VA	Virginia
WA	Washington
WV	West Virginia
WI	Wisconsin
WY	Wyoming
DC	District of Columbia
AS	American Samoa
GU	Guam
MP	Northern Mariana Islands
PR	Puerto Rico
UM	United States Minor Outlying Islands
VI	Virgin Islands, U.S.
```

**Comment by imathews** [comment] 2019-12-04 16:27
Thanks @johardi, confirmed. We have a release scheduled for Jan 6 that will include several updates to metadata handling, and will make sure that this is resolved in there.

@Sherri010 could you check to make sure this is resolved in the dev build? This is when pasting the above values into the valueList editor (after Georgia, the values don't show up)

**Comment by Sherri010** [comment] 2019-12-04 16:35
@imathews absolutely

**Comment by imathews** [comment] 2020-01-10 17:02
This is resolved in the latest release (thanks @Sherri010!) https://github.com/redivis/meta/releases/tag/0.15.0

**Closed by imathews** 2020-01-10 17:02 UTC
