### ISSUE TITLE
Default project view cuts off some nodes

### ISSUE THREAD

**Issue by llamsam** [redivis/meta#96] opened 2017-10-26 16:44 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Browser** (e.g., Chrome, Safari, etc.): Firefox

**What happened**: The default view upon entering a project cuts off the left-most set of nodes in my project. They are still half visible, but it is not ideal. 

**What you expected to happen**: All of the nodes would be entirely within my view upon entering a project.

**How to reproduce it** (as minimally and precisely as possible): Open up a project, preferably with lots of nodes.

**Anything else do we need to know**: Maybe I could just side-scroll and the problem would be fixed, but I do not have a side-scrolling mouse to test this theory.

**Comment by imathews** [comment] 2017-10-26 17:48
Hi @llamsam - thanks for this. I imagine this is similar to what you're seeing in #95. Do you mind sending a screenshot (either here, or if preferred, via email) of what this looks like? Are you by chance on windows? I'm not able to reproduce this on my computer, but imagine it could be due to browser + os and/or window size.

**Comment by llamsam** [comment] 2017-10-26 17:52
I am using OS X... screenshots sent via email. Thanks.

**Comment by imathews** [comment] 2017-10-26 19:03
Thanks — this isn't happening to any of us, but clearly a real bug. We'll work to recreate and fix.

And yes, there is horizontal scrolling functionality, but we'll add mechanisms to scroll for those without a side-scrolling mouse. As a temporary fix, you can click on the minimap and then use the arrow keys to navigate.

**Comment by imathews** [comment] 2017-11-05 02:32
See #95; this is fixed in https://github.com/redivis/meta/releases/tag/0.3.0

**Closed by imathews** 2017-11-05 02:32 UTC
Labels: bug
