### ISSUE TITLE
Layout change on Demo Project

### ISSUE THREAD

**Issue by vmeau** [redivis/meta#73] opened 2017-08-07 18:48 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Browser** (e.g., Chrome, Safari, etc.): Chrome

**What happened**: I am curious to understand why sometimes a project will first appear with Stanford's colors (dark red when I highlight code, etc.), and why sometimes - after I refresh for example - it will default to Redivis' blue colors (light blue when I highlight code). 

**What you expected to happen**: I'd like for it to retain the Stanford colors, especially for the demo on 08/15

**How to reproduce it** (as minimally and precisely as possible): Create a new project, create a transform, and refresh a few times. 

**Anything else do we need to know**: Here are two pictures showing the different colors between pre/post refresh 

![screen shot 2017-08-07 at 11 47 02 am](https://user-images.githubusercontent.com/22604632/29041057-4ef6bde6-7b66-11e7-959b-2182bbf8351c.png)

![screen shot 2017-08-07 at 11 47 14 am](https://user-images.githubusercontent.com/22604632/29041052-4373d3b4-7b66-11e7-9000-e38e0aa67844.png)

**Comment by imathews** [comment] 2017-08-12 01:22
@vmeau the intended behavior here is that this uses the Redivis colors (since your project isn't _necessarily_ specific to any one org). 

This inconsistency is a bug and is fixed in v0.2.0

**Closed by imathews** 2017-08-12 01:22 UTC
