### ISSUE TITLE
invalid input value for enum "enum_Variables_type": "generator"

### ISSUE THREAD

**Issue by JKoltsov** [redivis/meta#116] opened 2017-12-11 23:13 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Browser** (e.g., Chrome, Safari, etc.):
Chrome

**What happened**:
Ran a fairly simple pull on the Truven Outpatient services data.  Kept EnrolID and SVCdate, wanted to sum the costs for each patient and svcdate (selected no duplicates, summed Pay) for patient that had the proc code specified.
Got error:  invalid input value for enum "enum_Variables_type": "generator"

**What you expected to happen**:
see above

**How to reproduce it** (as minimally and precisely as possible):
see above
proc1 = 27650
drop duplicates on
new aggregate variable name costs, aggregate method sum, expression PAY (did not and cannot change distinct and over toggles, don't know what those do...) Clicked run.

**Anything else do we need to know**:

**Comment by imathews** [comment] 2017-12-12 00:15
Hi @JKoltsov thanks for the bug report! I believe that this was caused by an older error that should now be fixed — if you delete & recreate the aggregate variable, does it then run? You can delete the field by click on the context menu (see screenshot below):
![screen shot 2017-12-11 at 4 14 31 pm](https://user-images.githubusercontent.com/5659375/33860578-63659316-de8e-11e7-90e5-9d11a83aa572.png)

**Comment by JKoltsov** [comment] 2017-12-12 00:43
I did delete and try again earlier today.  Still didn't work....

Sent from my iPhone

On Dec 11, 2017, at 4:15 PM, Ian Mathews <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @JKoltsov<https://github.com/jkoltsov> thanks for the bug report! I believe that this was caused by an older error that should now be fixed — if you delete & recreate the aggregate variable, does it then run? You can delete the field by click on the context menu (see screenshot below):
[screen shot 2017-12-11 at 4 14 31 pm]<https://user-images.githubusercontent.com/5659375/33860578-63659316-de8e-11e7-90e5-9d11a83aa572.png>

**Comment by imathews** [comment] 2017-12-12 01:29
@JKoltsov hmm this is strange... when testing your project locally, I've been able to get this to work after deleting and recreating the aggregate variable.

One last thought — can you try giving the page a hard reload / open in a new window, and then deleting and recreating? If that doesn't work, we can follow up offline to get this sorted.

**Comment by imathews** [comment] 2017-12-19 18:28
I believe this should be fixed. @JKoltsov, please feel free to reopen if this is still presenting a problem

**Closed by imathews** 2017-12-19 18:28 UTC
